### ISSUE TITLE
Doesn’t remember scroll position in tabs when navigating

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/DroidconKotlin#108]
Assume this is when selecting different bottom nav, going back to the schedule resets all. Should probably implement a more standard nav control. Possibly try out the jetpack nav thing?

**Comment by kpgalligan** [comment]
Scroll schedule

![Screenshot_1562339021](https://user-images.githubusercontent.com/68384/60731112-ae10a700-9f14-11e9-8586-9214d6b925e9.png)

Nav to other tab

![Screenshot_1562339029](https://user-images.githubusercontent.com/68384/60731122-b5d04b80-9f14-11e9-97ff-48645774936a.png)

Nav back. Scrolled to top

![Screenshot_1562339032](https://user-images.githubusercontent.com/68384/60731126-b9fc6900-9f14-11e9-8c9d-085951d8d7ec.png)

**Comment by KevinSchildhorn** [comment]
There is a PR up for this issue (PR #111 )
