### ISSUE TITLE
Failed to resolve: co.touchlab:firestore:0.2.1

### ISSUE THREAD

**Issue by joreilly** [touchlab/DroidconKotlin#124]
Getting `Failed to resolve: co.touchlab:firestore:0.2.1` error when I try to build latest code.

**Comment by kpgalligan** [comment]
Sorry. I need to push the update

**Comment by kpgalligan** [comment]
That version was a "publishToMavenLocal"

**Comment by kpgalligan** [comment]
All updated!

**Comment by TheReprator** [comment]
'firestoreKmp' : '0.2.8-mt2',
'firestoreKmp' : "co.touchlab:firestore:${versions.firestoreKmp}"

In Lib gradle,
implementation deps.firebase.firestoreKmp


it's not resolved by gradle, please assist me with this
