### ISSUE TITLE
Async way to getData from Firestore

### ISSUE THREAD

**Issue by jarroyoesp** [touchlab/DroidconKotlin#135]
Hi, first of all thank you for this library!

But I have a question, is there any way to get data from Firestore without callbacks? Are you thinking to develop it?

```
getFirebaseInstance()
                .collection("sponsors-sf-2019")
                .orderBy("displayOrder")
                .get_()
                .addListeners(...)
```

**Comment by kpgalligan** [comment]
Like a direct call or coroutines? You can use coroutines to call `get_()`.

https://github.com/touchlab/FirestoreKMP/blob/master/firestore/src/commonMain/kotlin/co/touchlab/firebase/firestore/Query.kt#L36

```
getFirebaseInstance()
.collection("sponsors-sf-2019")
.orderBy("displayOrder")
.suspendGet()
```

That's a suspend method, so it needs to be inside a coroutine, but will work.

**Comment by jarroyoesp** [comment]
Hi @kpgalligan, "SuspendGet()" is what I need! Thank you for your quick response! 👏🏼
