### ISSUE TITLE
App routinely forgets "My Agenda"

### ISSUE THREAD

**Issue by DavidR-sevenbel** [touchlab/DroidconKotlin#153]
I'm at Droidcon right now, and am trying to track my planned schedule in this app. I am using the "My Agenda" feature, and have marked sessions and workshops for all three days.

The app has forgotten my schedule twice already, and I have to find the sessions again, so I can add them to "My Agenda" again.

I do not know what causes this, but it could be related to internet connectivity problems. I am using this app on a phone without a SIM card (--> phone has no internet if it isn't connected to WiFi).

Phone: Samsung Galaxy A71, running Android 11 / OneUI 3.1 with the August 2021 security patch.

**Comment by kpgalligan** [comment]
Fix on it's way. 2.0.5. Issue was with db logic.

https://github.com/touchlab/DroidconKotlin/commit/5a82452228dd978c1846110126224bdcd7b17a20
