### ISSUE TITLE
Keep getting notifications

### ISSUE THREAD

**Issue by TWiStErRob** [touchlab/DroidconKotlin#159]
When I restart the phone, or turn internet on/off, not sure, but I've seen multiple notifications for all my talks come up days after the event. This happened about 3-4 times since 29 Oct.

Here's the last instance:

![Screenshot_20211224-203811.png](https://user-images.githubusercontent.com/2906988/147370423-a70bd920-d54f-4c74-b186-40564b50db27.png)

**Comment by KatieGalvin** [comment]
potentially related to double notifications ticket

**Comment by TWiStErRob** [comment]
Potentially, but also this issue is from last year.
