### ISSUE TITLE
Droidcon London 2022 schedule 

### ISSUE THREAD

**Issue by emartynov** [touchlab/DroidconKotlin#181]
Hi people,

Do you plan to release 2022 schedule?

Kind Regards,
Eugen

**Comment by TadeasKriz** [comment]
Hi @emartynov,

do you mean Droidcon London 2022 schedule? If so, there will be a new release soon-ish.

**Comment by emartynov** [comment]
Sorry, yes, I meant Droidcon London 2022. I just downloaded the app from Google Play.

**Comment by KatieGalvin** [comment]
hi @emartynov, the apps for Droidcon London 2022 can now be found in the App store and Google Play store. Enjoy the conference!
