### ISSUE TITLE
Update Compose to 1.2.1 and Kotlin to 1.7.20

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/DroidconKotlin#193]
JB's Compose version has been updated to 1.2.1 (https://github.com/JetBrains/compose-jb/releases/tag/v1.2.1), which supports Kotlin 1.7.20. We should update the app and see how Compose performs.

Once updated, we should try it out on devices to see if there are performance improvements, and look at the binary size to see if that has improved.

**Comment by samhill303** [comment]
Version updates appear to be covered by #139 and PR #189. But leaving this here for profiling performance and size
