### ISSUE TITLE
Can't find SQLiter dependency

### ISSUE THREAD

**Issue by dhoskins** [touchlab/DroidconKotlin#39]
Hi

I am trying to build and run the iOS app, and got two errors on running `./gradlew build`. The first related to failure to find `sessionize/app/release.jks`, so I created that.

Following that was a failure to find `co.touchlab.sqliter:sqliter:0.1.1-k1.3.0-a6`, this could not be found in any of the repositories.

I assume this needs to succeed before I can build the iOS app in Xcode, because the Run Script phase there is looking for the folder `sessionize/lib/build/xcode-frameworks`.

Is there a missing repository for sqliter library?

**Comment by kpgalligan** [comment]
Hmm. I think that got caught in the shuffle to publish for Droidcon SF. I'm in the middle of updating the app now to reflect current versions. Sqldelight RC3 just got released, with a more official Sqliter release. Going to try to update all of them today. The version that's missing publicly was obviously just deployed locally and never pushed.

**Comment by kpgalligan** [comment]
If I can't update everything, I'll figure out an interim push later.

**Comment by kpgalligan** [comment]
Sorry on delay here. We've been refactoring the sqliter/sqldelight stuff more aggressively. I pushed a version last night that should build. However, AFTER a build you need to rerun the sqldelight generate task again. Somehow the generated source is getting deleted at the end of the build. Work ongoing.
