### ISSUE TITLE
Only one Kotlin framework can be loaded currently

### ISSUE THREAD

**Issue by kagile** [touchlab/DroidconKotlin#57]
After running the app on Android, it works fine.

But on iOS, application crashes with following:
`Only one Kotlin framework can be loaded currently.`

Maybe it is because of two frameworks linked - main and lib.

It has also been reported here, but I'm curious if you have any solution:
https://github.com/JetBrains/kotlin-native/issues/2423

**Comment by KevinSchildhorn** [comment]
Are you still seeing this issue? I believe we only have one kotlin framework so there should only be the lib framework now.
